name: Update GitHub Profile Repos

on:
  schedule:
    - cron: '0 0 * * *' # daily
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Repository Lists
        uses: tibdex/github-readme-repo-list-action@v2
        id: repos
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          visibility: public
          starred_first: true
          layout: grid
          per_row: 3
          show_description: true
          show_language: true
          show_last_update: false
          theme: default # can also use "dark" for dark mode

      - name: Update README
        run: |
          echo "# Hi 👋, I'm JH4CK3R CEO OF J PROJECT PLATFORM" > README.md
          echo -e "\nWelcome to J Project Platform GitHub profile! Here are all my repositories:\n" >> README.md
          echo "## 🌟 Starred Repositories" >> README.md
          echo "${{ steps.repos.outputs.starred }}" >> README.md
          echo -e "\n## 📂 Other Repositories" >> README.md
          echo "${{ steps.repos.outputs.other }}" >> README.md

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update repository list" || echo "No changes to commit"
          git push
